### ISSUE TITLE
User is not authorized to access this resource with an explicit deny 

### ISSUE THREAD

**Issue by nayabrasool4910** [amazon-connect/amazon-connect-chatjs#114]
I import amazon-connect-chatjs library in my code.

with the help of library I am trying to get Customer messages, Sending Messages from Agent side but I am getting this error because its connecting to 'us-west-2' but I gave 'us-east-1' in my code 

**myCode**

import "amazon-connect-streams";
import "amazon-connect-chatjs"

contact.onAccepted(() => {
        const cnn = contact.getAgentConnection() as connect.ChatConnection;
        console.log(cnn)
    
        const agentChatSession = connect.ChatSession.create({
          chatDetails: cnn.getMediaInfo(), // REQUIRED
          options: { // REQUIRED
            region: "us-east-1", // REQUIRED, must match the value provided to `connect.core.initCCP()`
          },
          type: connect.ChatSession.SessionTypes.AGENT, // REQUIRED
          websocketManager: connect.core.getWebSocketManager() // REQUIRED
        });

        console.log(agentChatSession)

        agentChatSession.onMessage((response) => {
          console.log(response)
        })
        
        agentChatSession.sendMessage({message:'so and so', content:'text/plain' }).then((res) => { console.log(res) })

      });

core.js:4442 ERROR Error: Uncaught (in promise): Object: {"reason":"Failed to fetch connectionDetails with createParticipantConnection","_debug":{"type":"UnknownError","message":"User is not authorized to access this resource with an explicit deny","stack":["UnknownError: User is not authorized to access this resource with an explicit deny","    at Object.extractError (https://10.224.58.9:4200/vendor.js:16616:97122)","    at constructor.extractError (https://10.224.58.9:4200/vendor.js:16616:102318)","    at constructor.callListeners (https://10.224.58.9:4200/vendor.js:16616:120044)","    at constructor.emit (https://10.224.58.9:4200/vendor.js:16616:119755)","    at constructor.emitEvent (https://10.224.58.9:4200/vendor.js:16616:113435)","    at constructor.e (https://10.224.58.9:4200/vendor.js:16616:108941)","    at r.runTo (https://10.224.58.9:4200/vendor.js:16616:146652)","    at https://10.224.58.9:4200/vendor.js:16616:146858","    at constructor.<anonymous> (https://10.224.58.9:4200/vendor.js:16616:109230)","    at constructor.<anonymous> (https://10.224.58.9:4200/vendor.js:16616:113491)"],"statusCode":403}}
    at resolvePromise (zone-evergreen.js:798:1)
    at resolvePromise (zone-evergreen.js:750:1)
    at zone-evergreen.js:860:1
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Object.onInvokeTask (core.js:27533:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
    at Zone.runTask (zone-evergreen.js:167:1)
    at drainMicroTaskQueue (zone-evergreen.js:569:1)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484:1)
    at invokeTask (zone-evergreen.js:1621:1)

POST https://participant.connect.us-west-2.amazonaws.com/participant/connection 403
POST https://participant.connect.us-west-2.amazonaws.com/participant/event 403
POST https://participant.connect.us-west-2.amazonaws.com/participant/messages 403

Can any one Know where I did mistake.

**Comment by mhiaror** [comment]
Please follow the documentation here https://github.com/amazon-connect/amazon-connect-chatjs#connectchatsessionsetglobalconfig

Can you make sure you are calling `setGlobalConfig` and passing correct region. If region param is not set; it defaults to `us-west-2`. 
```
region: "us-east-1", // optional, defaults to: "us-west-2"
```

**Comment by nayabrasool4910** [comment]
Thanks for your response @mhiaror . I am still getting the same error. My Code. I am trying to send message from AgentChatSession through button. 

import "amazon-connect-streams";
import "amazon-connect-chatjs"

ngOnInit(): void {

    connect.ChatSession.setGlobalConfig({
        region: "us-east-1", // optional, defaults to: "us-west-2"
     });

    contact.onConnecting(function (c) {
          console.log("incoming");
          // c.accept();
        });

        contact.onAccepted(async () => {
          const cnn = contact.getAgentConnection() as connect.ChatConnection
          if(cnn){
          const agentChatSession = await cnn.getMediaController();
          agentChatSession.onMessage((res)=>{
            let token = res.chatDetails.participantToken
            console.log(res)
          });

          agentChatSession.sendMessage({ message:'text', contentType: 'text/plain' }).then((res) =>{
            console.log(res.status)
          })
          console.log(cnn)
          }

        });




}

**Comment by mhiaror** [comment]
Initializing the Streams API is the first step to verify that you have everything setup correctly and that you will be able to listen for events.

-- you also need to follow Streams documentation:

https://github.com/amazon-connect/amazon-connect-streams#connectcoreinitccp
```
connect.core.initCCP(containerDiv, {
          region: "eu-central-1",  
```

**Comment by nayabrasool4910** [comment]
Thanks @mhiaror resolved my issue.
